# Este dockerfile permite demostrar junto con el archivo
# /docker/production/dockerfile que es una práctica común
# utilizar dos dockerfile distintos para generar imágenes
# para distintos casos de uso.
# 
# En escenarios como estos en los que existen distintos archivos
# dockerfile, el archivo .dockerignore tendrá que ubicarse al
# nivel del dockerfile en cuestión, además tendrá que configurarse
# en la shell la variable de entorno export DOCKER_BUILDKIT=1 y
# el comando $ docker tendrá que ejecutarse específicamente desde
# el directorio que contiene a ambos archivos, teniendo que establecer
# por consecuencia el build context retrocediendo en la ruta
# relativa (../../). Considerar lo siguiente:
# 
#   Según la documentación oficial, apoyandose del build-context 
#   definido para el comando $ docker run, para el archivo
#   MyStage.dockerfile entonces Docker buscará a MyStage.dockerignore,
#   y de no encontrarlo, irá a buscar .dockerignore directamente.
# 
# Existen peticiones en curso que solicitan la adición de una
# bandera que permita indicar al .dockerignore tal y como se
# hace con dockerfile mediante el argumento --file (-f).

FROM node:latest

COPY ["package.json", "package-lock.json", "/usr/src/"]

WORKDIR /usr/src

RUN npm install

COPY [".", "/usr/src/"]

CMD ["npm", "run", "serve"]