# Un dockerfile sirve para crear una imagen personalizada
# y controlar paso a paso la construcción de las capas de la
# imagen.
# 
# Por cada sentencia escrita (RUN, WORKDIR, etc.) se está creando
# una capa nueva en la imagen. En sentencias como RUN, Docker incluso
# crea contenedores temporales que corran la imagen base y ejecuten los
# comandos indicados para luego destruir dicho contenedor.

# Un dockerfile siempre comenzará indicando a través de su sentencia FROM una
# imagen existente cualquiera que utilizará como base, como por ejemplo Debian,
# Red Hat, Node, nginx etc.
# 
# Más sobre sintaxis de dockerfile:
# + https://docs.docker.com/engine/reference/builder/
FROM ubuntu:latest

# Ejecutando un comando...
# 
# La sentencia RUN ejecuta un comando cualquiera en tiempo de build (momento en
# que una imagen está siendo construida) utilizando la shell de la imagen
# en cuestión, es decir, para una imagen de Linux utilizaría una shell bash o
# similares, mientras que en una imagen de Windows utilizaría PowerShell.
# 
# En este caso en particular, la sentencia RUN está ejecutando un comando que
# creará un archivo llamado hello-world.txt en el directorio /usr/src/.
# 
# La construicción de la imagen fallará cuando se trate de ejecutar un comando
# interactivo, es decir, un comando que requiere de la interacción de un usuario,
# como por ejemplo
# 
#                       $ apt install some-package
# 
# , el cual siempre solicita la confirmación de instalación, en cuyo caso habrá que
# reemplazar por
# 
#                     $ apt install -y some-package
# 
RUN touch /usr/src/hello-world.txt